name: ci
on:
  push:
  pull_request:

jobs:
  go:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    defaults:
      run:
        working-directory: tui
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: tui/go.mod
      - run: go build ./...
